spring.application.name=RedeSocial

spring.datasource.url=jdbc:postgresql://localhost:5433/RedeSocial
spring.datasource.username=postgres
spring.datasource.password=minhasenha123
spring.jpa.hibernate.ddl-auto=update
